from . import patients
from . import doctors
from . import appointments
from . import records
from . import billing
from . import inventory
from . import auth
from . import system
from . import analytics_dashboard
