"""Adds user table

Revision ID: 4760d498899b
Revises: 
Create Date: 2025-07-14 12:29:17.315483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4760d498899b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role_', table_name='users')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=True)
    op.drop_column('users', 'role_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index('ix_users_role_', 'users', ['role_'], unique=1)
    # ### end Alembic commands ###
